# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: docker_mysql_mysql # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=root   #コンテナ内のMySQLを起動する際のパスワードを設定
      - TZ='Asia/Tokyo'
    ports:
      - '3306:3306'
    container_name: docker_mysql_mysql_1